name: chatapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  emoji_picker_flutter: ^4.3.0
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7
  flutter_gemini: ^3.0.0
  path_provider: ^2.1.3 

  flutter_localizations:
    sdk: flutter   
  google_generative_ai: ^0.4.7
  lottie: ^3.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/


  generate: true

 